#!/bin/bash

KERB="${1:-}"

if [[ -z "$KERB" ]]; then
  echo "Usage: $0 <kerberos>"
  exit 1
fi

echo "### Building Vite app... ###"
yarn run build

echo "### Copying ./dist to ${KERB}@athena.dialup.mit.edu:/mit/zbt/web_scripts_new/ ###"
scp -r dist/* "${KERB}@athena.dialup.mit.edu:/mit/zbt/web_scripts_new/"

echo "### Backing up old files and setting permissions for new files... ###"
ssh "${KERB}@athena.dialup.mit.edu" bash /mit/zbt/clean_backup_deploy.sh

echo "### Deploy complete. Hard-refresh your browser to see changes. ###"